OPENAI_API_KEY = "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"
SHOPIFY_API_KEY = "eec9b509f0eea387bc84f2f552959c18"
SHOPIFY_ACCESS_TOKEN = "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"
SHOPIFY_SHOP_URL = "5tph5b-u3.myshopify.com"
